from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
from app.database import get_db
from app import models, schemas
from app.auth import get_current_user 

router = APIRouter(
    prefix="/care-team",
    tags=["Care Team & Doctors"]
)

# ==========================================
# 1. GET LINKED DOCTORS (My Doctors Page)
# ==========================================
@router.get("/doctors", response_model=List[schemas.DoctorOut])
def get_my_doctors(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all doctors that the user has saved to their Care Team."""
    
    # Query the PersonalDoctor junction table to find the user's linked doctors
    linked_doctors = db.query(models.Doctor).join(
        models.PersonalDoctor, models.Doctor.id == models.PersonalDoctor.doctor_id
    ).filter(
        models.PersonalDoctor.user_id == current_user.id
    ).all()
    
    # Map the DB fields to match what Flutter expects
    for doc in linked_doctors:
        doc.qualifications = doc.education # Mapping education to qualifications for the UI
        
    return linked_doctors

# ==========================================
# 2. GET APPOINTMENTS (Appointments Tab)
# ==========================================
@router.get("/appointments", response_model=List[schemas.AppointmentOut])
def get_my_appointments(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all appointments for the logged-in user."""
    
    appointments = db.query(models.Appointment).filter(
        models.Appointment.user_id == current_user.id
    ).order_by(models.Appointment.appointment_time.asc()).all()
    
    return appointments

# ==========================================
# 3. BOOK APPOINTMENT
# ==========================================
@router.post("/appointments", response_model=schemas.AppointmentOut)
def book_appointment(appt: schemas.AppointmentCreate, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Creates a new appointment request."""
    
    # Verify the doctor exists
    doctor = db.query(models.Doctor).filter(models.Doctor.id == appt.doctor_id).first()
    if not doctor:
        raise HTTPException(status_code=404, detail="Doctor not found")

    new_appt = models.Appointment(
        user_id=current_user.id,
        doctor_id=appt.doctor_id,
        appointment_time=appt.appointment_time,
        purpose=appt.purpose,
        status="Upcoming"
    )
    
    db.add(new_appt)
    db.commit()
    db.refresh(new_appt)
    
    return new_appt

# ==========================================
# 4. GET MEDICAL RECORDS (Records Tab)
# ==========================================
@router.get("/records", response_model=List[schemas.MedicalRecordOut])
def get_my_records(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all medical records for the user."""
    
    records = db.query(models.MedicalRecord).filter(
        models.MedicalRecord.user_id == current_user.id
    ).order_by(models.MedicalRecord.created_at.desc()).all()
    
    return records

# ==========================================
# 5. SAVE MEDICAL RECORD
# ==========================================
@router.post("/records", response_model=schemas.MedicalRecordOut)
def save_medical_record(record: schemas.MedicalRecordCreate, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """
    Saves the metadata for an uploaded document.
    Note: The actual file upload (PDF/Image) to S3/Cloud should happen first, 
    and this endpoint receives the secure URL generated by that upload.
    """
    
    new_record = models.MedicalRecord(
        user_id=current_user.id,
        doctor_id=record.doctor_id,
        file_name=record.file_name,
        record_type=record.record_type,
        file_url=record.file_url,
        description=record.description
    )
    
    db.add(new_record)
    db.commit()
    db.refresh(new_record)
    
    return new_record

# ==========================================
# 6. SEARCH DOCTORS DIRECTORY
# ==========================================
@router.get("/search", response_model=List[schemas.DoctorOut])
def search_doctors(
    q: str = "", 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Searches the global database for doctors by name, specialty, or clinic."""
    search_term = f"%{q}%"
    
    # Searches across name, specialisation, and clinic
    doctors = db.query(models.Doctor).filter(
        (models.Doctor.name.ilike(search_term)) | 
        (models.Doctor.specialisation.ilike(search_term)) |
        (models.Doctor.clinic_name.ilike(search_term))
    ).all()
    
    for doc in doctors:
        doc.qualifications = doc.education
        
    return doctors

# ==========================================
# 7. LINK DOCTOR TO USER
# ==========================================
@router.post("/link")
def link_doctor(
    req: schemas.LinkDoctorRequest, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Adds a doctor to the user's personal Care Team."""
    # Check if they are already linked
    existing_link = db.query(models.PersonalDoctor).filter(
        models.PersonalDoctor.user_id == current_user.id,
        models.PersonalDoctor.doctor_id == req.doctor_id
    ).first()
    
    if not existing_link:
        new_link = models.PersonalDoctor(
            user_id=current_user.id, 
            doctor_id=req.doctor_id
        )
        db.add(new_link)
        db.commit()
        
    return {"message": "Doctor linked successfully"}