from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
from app.database import get_db
from app import models, schemas
from app.auth import get_current_user 
import boto3
from botocore.client import Config
import os
import uuid

router = APIRouter(
    prefix="/care-team",
    tags=["Care Team & Doctors"]
)

s3_client = boto3.client(
    's3',
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name=os.getenv("AWS_REGION"),
    endpoint_url=f"https://s3.{os.getenv('AWS_REGION')}.amazonaws.com",
    config=Config(signature_version='s3v4')
)
BUCKET_NAME = os.getenv("S3_BUCKET_NAME")

# ==========================================
# 1. GET LINKED DOCTORS (My Doctors Page)
# ==========================================
@router.get("/doctors", response_model=List[schemas.DoctorOut])
def get_my_doctors(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all doctors that the user has saved to their Care Team."""
    
    # Query the PersonalDoctor junction table to find the user's linked doctors
    linked_doctors = db.query(models.Doctor).join(
        models.PersonalDoctor, models.Doctor.id == models.PersonalDoctor.doctor_id
    ).filter(
        models.PersonalDoctor.user_id == current_user.id
    ).all()
    
    # Map the DB fields to match what Flutter expects
    for doc in linked_doctors:
        doc.qualifications = doc.education # Mapping education to qualifications for the UI
        
    return linked_doctors

# ==========================================
# 2. GET APPOINTMENTS (Appointments Tab)
# ==========================================
@router.get("/appointments")
def get_my_appointments(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all appointments for the logged-in user, including doctor details."""
    
    # We join the models.Doctor table so we can grab the doctor's name!
    results = db.query(models.Appointment, models.Doctor).join(
        models.Doctor, models.Appointment.doctor_id == models.Doctor.id
    ).filter(
        models.Appointment.user_id == current_user.id
    ).order_by(models.Appointment.appointment_time.asc()).all()
    
    appointments_list = []
    for appt, doc in results:
        appointments_list.append({
            "id": appt.id,
            "appointment_time": appt.appointment_time.isoformat() if appt.appointment_time else None,
            "status": appt.status,
            "purpose": appt.purpose,
            "doctor": {
                "name": doc.name,
                "preferred_name": doc.preferred_name,
                "specialisation": doc.specialisation
            }
        })
    
    return appointments_list

# ==========================================
# 3. BOOK APPOINTMENT
# ==========================================
@router.post("/appointments", response_model=schemas.AppointmentOut)
def book_appointment(appt: schemas.AppointmentCreate, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Creates a new appointment request."""
    
    # Verify the doctor exists
    doctor = db.query(models.Doctor).filter(models.Doctor.id == appt.doctor_id).first()
    if not doctor:
        raise HTTPException(status_code=404, detail="Doctor not found")

    new_appt = models.Appointment(
        user_id=current_user.id,
        doctor_id=appt.doctor_id,
        appointment_time=appt.appointment_time,
        purpose=appt.purpose,
        status="Upcoming"
    )
    
    db.add(new_appt)
    db.commit()
    db.refresh(new_appt)
    
    return new_appt

# ==========================================
# 4. GET MEDICAL RECORDS (Records Tab)
# ==========================================
@router.get("/records", response_model=List[schemas.MedicalRecordOut])
def get_my_records(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Fetches all medical records for the user."""
    
    records = db.query(models.MedicalRecord).filter(
        models.MedicalRecord.user_id == current_user.id
    ).order_by(models.MedicalRecord.created_at.desc()).all()
    
    return records

# ==========================================
# 5. SAVE MEDICAL RECORD
# ==========================================
@router.post("/records", response_model=schemas.MedicalRecordOut)
def save_medical_record(record: schemas.MedicalRecordCreate, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """
    Saves the metadata for an uploaded document.
    Note: The actual file upload (PDF/Image) to S3/Cloud should happen first, 
    and this endpoint receives the secure URL generated by that upload.
    """
    
    new_record = models.MedicalRecord(
        user_id=current_user.id,
        doctor_id=record.doctor_id,
        file_name=record.file_name,
        record_type=record.record_type,
        file_url=record.file_url,
        description=record.description
    )
    
    db.add(new_record)
    db.commit()
    db.refresh(new_record)
    
    return new_record

# ==========================================
# 6. SEARCH DOCTORS DIRECTORY
# ==========================================
@router.get("/search", response_model=List[schemas.DoctorOut])
def search_doctors(
    q: str = "", 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Searches the global database for doctors by name, specialty, or clinic."""
    search_term = f"%{q}%"
    
    # Searches across name, specialisation, and clinic
    doctors = db.query(models.Doctor).filter(
        (models.Doctor.name.ilike(search_term)) | 
        (models.Doctor.specialisation.ilike(search_term)) |
        (models.Doctor.clinic_name.ilike(search_term))
    ).all()
    
    for doc in doctors:
        doc.qualifications = doc.education
        
    return doctors

# ==========================================
# 7. LINK DOCTOR TO USER
# ==========================================
@router.post("/link")
def link_doctor(
    req: schemas.LinkDoctorRequest, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Adds a doctor to the user's personal Care Team."""
    # Check if they are already linked
    existing_link = db.query(models.PersonalDoctor).filter(
        models.PersonalDoctor.user_id == current_user.id,
        models.PersonalDoctor.doctor_id == req.doctor_id
    ).first()
    
    if not existing_link:
        new_link = models.PersonalDoctor(
            user_id=current_user.id, 
            doctor_id=req.doctor_id
        )
        db.add(new_link)
        db.commit()
        
    return {"message": "Doctor linked successfully"}

# ==========================================
# 8. GET DOCTOR PERMISSIONS
# ==========================================
@router.get("/permissions/{doctor_id}")
def get_doctor_permissions(
    doctor_id: str, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Fetches the specific data access permissions for a linked doctor."""
    link = db.query(models.PersonalDoctor).filter(
        models.PersonalDoctor.user_id == current_user.id,
        models.PersonalDoctor.doctor_id == doctor_id
    ).first()

    if not link:
        raise HTTPException(status_code=404, detail="Doctor not found in your care team")

    return {
        "can_view_heart_rate": link.can_view_heart_rate,
        "can_view_blood_pressure": link.can_view_blood_pressure,
        "can_view_blood_glucose": link.can_view_blood_glucose,
        "can_view_oxygen_saturation": link.can_view_oxygen_saturation,
        "can_view_body_weight": link.can_view_body_weight,
        "can_view_medications": link.can_view_medications,
        "can_view_activity": link.can_view_activity
    }

# ==========================================
# 9. UPDATE DOCTOR PERMISSIONS
# ==========================================
@router.put("/permissions/{doctor_id}")
def update_doctor_permissions(
    doctor_id: str,
    perms: dict, # Accepts the JSON payload of boolean switches from Flutter
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Updates what data the doctor is allowed to see."""
    link = db.query(models.PersonalDoctor).filter(
        models.PersonalDoctor.user_id == current_user.id,
        models.PersonalDoctor.doctor_id == doctor_id
    ).first()

    if not link:
        raise HTTPException(status_code=404, detail="Doctor not found in your care team")

    # Update the permissions based on the incoming dictionary
    if 'can_view_heart_rate' in perms: link.can_view_heart_rate = perms['can_view_heart_rate']
    if 'can_view_blood_pressure' in perms: link.can_view_blood_pressure = perms['can_view_blood_pressure']
    if 'can_view_blood_glucose' in perms: link.can_view_blood_glucose = perms['can_view_blood_glucose']
    if 'can_view_oxygen_saturation' in perms: link.can_view_oxygen_saturation = perms['can_view_oxygen_saturation']
    if 'can_view_body_weight' in perms: link.can_view_body_weight = perms['can_view_body_weight']
    if 'can_view_medications' in perms: link.can_view_medications = perms['can_view_medications']
    if 'can_view_activity' in perms: link.can_view_activity = perms['can_view_activity']

    db.commit()
    return {"message": "Permissions updated successfully"}

# ==========================================
# 10. REMOVE DOCTOR FROM CARE TEAM
# ==========================================
@router.delete("/{doctor_id}")
def remove_linked_doctor(
    doctor_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    """Removes a doctor from the user's Care Team."""
    link = db.query(models.PersonalDoctor).filter(
        models.PersonalDoctor.user_id == current_user.id,
        models.PersonalDoctor.doctor_id == doctor_id
    ).first()

    if not link:
        raise HTTPException(status_code=404, detail="Doctor not found in your care team")

    db.delete(link)
    db.commit()
    
    return {"message": "Doctor removed successfully"}

# ==========================================
# 11. GENERATE UPLOAD URL (For Patients)
# ==========================================
@router.get("/records/upload-url")
def get_upload_url(
    file_name: str, 
    file_type: str, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Generates a secure 5-minute URL for the patient app to upload a file to S3."""
    # Create a unique file path: e.g., patients/42/uuid-bloodtest.pdf
    unique_filename = f"patients/{current_user.id}/{uuid.uuid4()}_{file_name}"
    
    try:
        presigned_url = s3_client.generate_presigned_url(
            'put_object',
            Params={
                'Bucket': BUCKET_NAME,
                'Key': unique_filename,
                'ContentType': file_type
            },
            ExpiresIn=300 # Valid for 5 minutes
        )
        
        return {
            "upload_url": presigned_url,
            "file_key": unique_filename # We will save this in the 'file_url' column later
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail="Could not generate upload URL")

# ==========================================
# 12. GENERATE VIEW/DOWNLOAD URL
# ==========================================
@router.get("/records/{record_id}/download-url")
def get_download_url(
    record_id: int, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """Generates a temporary URL to view a private file."""
    record = db.query(models.MedicalRecord).filter(
        models.MedicalRecord.id == record_id,
        models.MedicalRecord.user_id == current_user.id # Security check!
    ).first()
    
    if not record:
        raise HTTPException(status_code=404, detail="Record not found")

    try:
        presigned_url = s3_client.generate_presigned_url(
            'get_object',
            Params={
                'Bucket': BUCKET_NAME,
                'Key': record.file_url # We saved the unique key here during upload
            },
            ExpiresIn=3600 # Valid for 1 hour
        )
        return {"download_url": presigned_url}
    except Exception as e:
        raise HTTPException(status_code=500, detail="Could not generate download URL")